### Send PUT request with json body
PUT http://localhost:8080/developer/Micky12
Content-Type: application/json

{
  "developerLevel": "SENIOR",
  "developerSkillType": "FULL_STACK",
  "experienceYears": 19
}